### PR TITLE
Close #179: fix link thickness rendering

### LINKED ISSUE #179: Link thickness drawing incorrectly; it only changes the width of the link
Here is "Info Tab Example" in JVM NetLogo:

jvminfotab

Here it is in Tortoise, where the bottom-most turtle protrudes from the bottom of the arrow:

tortoiseinfotab

The labels prove that the turtles are in the correct locations.  The problem appears to be that link thickness in Beak is only changing the **width** of the drawn link, whereas it should also be extending the link's display towards the link ends.

### PR DESCRIPTION
**Pull request by skorlir**
Some caveats apply.

Covers most common cases where link extension occurs; doesn't cover cases such as, for instance, when the link wraps but the turtle at the end doesn't. Nor does it cover @qiemem 's weird case where the link wraps in all 3 directions but the turtle stays in the corner of the canvas.

[Review on Reviewable](https://reviewable.io/reviews/netlogo/galapagos/200)

### CODE REVIEW

File: app/assets/javascripts/TortoiseJS/agent/view.coffee [hunk 1]
```diff
@@ -248,17 +248,37 @@ class TurtleView extends View
     @ctx.lineTo(x2,y2)
 
   drawLink: (link, turtles, canWrapX, canWrapY) ->
+    shouldWrapInDim = (canWrap, worldMin, worldMax, cor1, cor2) ->
+      dist    = Math.abs(cor1 - cor2)
+      dimSize = worldMax - worldMin + 1
```
Comment (qiemem) [inline app/assets/javascripts/TortoiseJS/agent/view.coffee]: Dimensions are stored as `@patchWidth` and `@patchHeight`. Should probably use those instead (so, take an argument `dimension` or something)...

File: app/assets/javascripts/TortoiseJS/agent/view.coffee [hunk 2]
```diff
@@ -248,17 +248,37 @@ class TurtleView extends View
...
+      canWrap and dist > dimSize / 2
```
Comment (qiemem) [inline app/assets/javascripts/TortoiseJS/agent/view.coffee]: Way better than the previous inequality. Thanks!

File: app/assets/javascripts/TortoiseJS/agent/view.coffee [hunk 3]
```diff
@@ -248,17 +248,37 @@ class TurtleView extends View
...
+
+    adjustLinkEnds = (end1Cor, end2Cor, trigShift, minForExtending, maxForExtending) ->
+      diff = Math.abs(link.thickness * trigShift) / 2
```
Comment (qiemem) [inline app/assets/javascripts/TortoiseJS/agent/view.coffee]: Could probably be done with `atan2`, but whatevs.

**Comment by skorlir** [comment]
:tada: This is my first merged pull request ever with the CCL! (That took a long time, considering I never technically left from the Summer.)

**Comment by TheBizzle** [comment]
:tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada:
:tada: Party hats and confetti for everyone!!!  :tada:
:tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada::tada: :tada: :tada: :tada:
